package org.ops4j.pax.exam.mavenplugin;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.Map;
import org.apache.maven.artifact.Artifact;
import org.apache.maven.artifact.factory.ArtifactFactory;
import org.apache.maven.artifact.metadata.ArtifactMetadataSource;
import org.apache.maven.artifact.resolver.ArtifactCollector;
import org.apache.maven.artifact.resolver.ArtifactResolver;
import org.apache.maven.artifact.resolver.DefaultArtifactCollector;
import org.apache.maven.model.Dependency;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.project.MavenProject;

/**
 * @author Toni Menzel (tonit)
 * @goal generate-paxexam-config
 * @phase generate-resources
 * @since Mar 17, 2009
 */
public class ExamPlugin extends AbstractMojo
{

    protected static final String SEPARATOR = "/";

    /**
     * The maven project.
     *
     * @parameter expression="${project}"
     * @required
     * @readonly
     */
    protected MavenProject project;


    /**
     * The file to generate
     *
     * @parameter default-value="${project.build.directory}/classes/META-INF/maven/paxexam-config.args"
     */

    private File outputFile;

    /**
     * pax runner arguments defined in <settings> tag in configuration of plugin.
     *
     * @parameter
     */

    private Map settings;

    /**
     * @component
     */
    protected ArtifactMetadataSource artifactMetadataSource;

    /**
     * @component
     */
    protected ArtifactResolver resolver;

    protected ArtifactCollector collector = new DefaultArtifactCollector();

    /**
     * @component
     */
    protected ArtifactFactory factory;

    public void execute()
        throws MojoExecutionException, MojoFailureException
    {
        OutputStream out = null;
        try
        {
            outputFile.getParentFile().mkdirs();
            out = new FileOutputStream( outputFile );
            PrintStream printer = new PrintStream( out );

            List<Dependency> dependencies;
            dependencies = getProvisionableDependencies();

            writeHeader( printer );
            writeProvisioning( printer, dependencies );
            writeSettings( printer, settings );

            getLog().info( "PAX EXAM PLUGIN Created: " + outputFile );
        }
        catch( Exception e )
        {
            throw new MojoExecutionException(
                "Unable to create dependencies file: " + e, e
            );
        }
        finally
        {
            if( out != null )
            {
                try
                {
                    out.close();
                }
                catch( IOException e )
                {
                    getLog().info( "Failed to close: " + outputFile + ". Reason: " + e, e );
                }
            }
        }
    }

    private void writeHeader( PrintStream out )
    {
        out.println( "# Configurations generated by the Pax Exam Maven Plugin" );
        out.println( "# Generated at: " + new Date() );
        out.println();
        out.println( "# groupId = " + project.getGroupId() );
        out.println( "# artifactId = " + project.getArtifactId() );
        out.println( "# version = " + project.getVersion() );
        out.println( "# " +
                     project.getGroupId() + SEPARATOR + project.getArtifactId() + SEPARATOR + "version = "
                     + project.getVersion()
        );
        out.println();
    }

    private void writeSettings( PrintStream out, Map settings )
    {
        out.println( "# Settings parsed from pom.xml in settings of plugin" );
        for( Object key : settings.keySet() )
        {
            out.println( "--" + key + "=" + settings.get( key ) );
        }
        out.println();
    }

    /**
     * Dependency resolution inspired by servicemix depends-maven-plguin
     *
     * @return list of dependencies to be written to disk.
     */
    private List<Dependency> getProvisionableDependencies()
    {
        List<Dependency> dependencies = new ArrayList<Dependency>();
        for( Dependency d : (List<Dependency>) project.getDependencies() )
        {
            if( d.getScope() != null && d.getScope().equalsIgnoreCase( "provided" ) )
            {
                dependencies.add( d );
            }
        }

        Collections.sort( dependencies, new Comparator<Dependency>()
        {
            public int compare( Dependency o1, Dependency o2 )
            {
                int result = o1.getGroupId().compareTo( o2.getGroupId() );
                if( result == 0 )
                {
                    result = o1.getArtifactId().compareTo( o2.getArtifactId() );
                    if( result == 0 )
                    {
                        result = o1.getType().compareTo( o2.getType() );
                        if( result == 0 )
                        {
                            if( o1.getClassifier() == null )
                            {
                                if( o2.getClassifier() != null )
                                {
                                    result = 1;
                                }
                            }
                            else
                            {
                                if( o2.getClassifier() != null )
                                {
                                    result = o1.getClassifier().compareTo( o2.getClassifier() );
                                }
                                else
                                {
                                    result = -1;
                                }
                            }
                            if( result == 0 )
                            {
                                result = o1.getVersion().compareTo( o2.getVersion() );
                            }
                        }
                    }
                }
                return result;
            }
        }
        );
        return dependencies;
    }

    protected void writeProvisioning( PrintStream out, List<Dependency> dependencies )
    {

        out.println( "# provisioning" );
        out.println();

        Iterator iterator = dependencies.iterator();
        int i = 0;
        while( iterator.hasNext() )
        {
            Dependency dependency = (Dependency) iterator.next();
            String url = "mvn:" + dependency.getGroupId() + SEPARATOR + dependency.getArtifactId() + SEPARATOR
                         + dependency.getVersion();
            out.println( url );

            getLog().debug( "Dependency: " + dependency + " classifier: " + dependency.getClassifier() + " type: "
                            + dependency.getType()
            );
        }
        out.println();
    }

}

