/*
 * Copyright 2009 Toni Menzel.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ops4j.pax.exam.options;

import java.net.URL;
import org.ops4j.pax.exam.Option;

/**
 * Flag option
 *
 * @author Toni Menzel (tonit)
 * @since Mar 18, 2009
 */
public class MavenConfigurationOption implements Option
{

    private URL m_url;
    private static final String DEFAULT_CONFIGURATION = "META-INF/maven/paxexam-config.properties";

    public MavenConfigurationOption()

    {
        m_url = MavenConfigurationOption.class.getClassLoader().getResource( DEFAULT_CONFIGURATION );
    }

    /**
     * Support externally supplied configuration.
     *
     * @param url to be used to read the configuration from if you don't want to use the one generated by maven-paxexam-plugin.
     *
     * @return this for fluent api
     */
    public MavenConfigurationOption configuration( URL url )
    {
        m_url = url;
        return this;
    }

    public URL getURL()
    {
        return m_url;
    }
}
